"""
scrapengine/scrapers/rss.py tests
"""
import os
import unittest
import requests
import feedparser
from Scrapengine.scrapers import rss as rss_scraper
from Scrapengine.configs import ARCHIVE

class RssScraperTestCase(unittest.TestCase):
    
    def setUp(self,):
        from Scrapengine.configs import SCRAPERS
        self.rss_source = SCRAPERS['rss']['allafrica.com.africa']
        self.parsed_response = self._get_source()
        self.entries = self._get_entries()

    def _get_source(self,):
        return rss_scraper.get_source(self.rss_source)

    def _get_entries(self,):
        return rss_scraper.get_entries(self.parsed_response)
    
    def test_get_source(self,):
        # first check integrity of http source
        httpresp = requests.get(self.rss_source)
        self.assertTrue(httpresp.status_code == 200, msg="Cannot get %s. HTTP error %s" % (
            self.rss_source, str(httpresp.status_code)))
        del httpresp

        # check response type
        self.assertIsInstance(self.parsed_response,
                feedparser.FeedParserDict, msg="Unexpected object type %s for %s" %
                (type(self.parsed_response), self.parsed_response))

    def test_response_attributes(self,):
        self.assertIn('feed', self.parsed_response)
        self.assertIn('entries', self.parsed_response)
        feed_metadata = self.parsed_response['feed']
        feed_entries = self.parsed_response['entries']
        for entry in feed_entries:
            self.assertIn('title', entry)
            self.assertIn('summary', entry)
            self.assertIn('link', entry)

    def test_get_entries(self,):
        for entry in self.entries:
            self.assertIsInstance(entry, dict)

    def test_output_csv(self,):
        files = os.listdir(ARCHIVE) # list files
        for _file in files:
            if _file.endswith('csv') and _file.startswith('tests'):
                # delete output files generated by the unit tests
                os.remove("%s/%s" % (ARCHIVE, _file))
        
        rss_scraper.output(self.entries, destination='csv', source='tests')

        generated = False
        for _file in os.listdir(ARCHIVE):
            if _file.endswith('csv') and _file.startswith('rss-tests'):
                # file generated. break
                generated = True
                os.remove("%s/%s" % (ARCHIVE, _file))
        self.assertTrue(generated, msg="Output not generated")



if __name__ == '__main__':
    unittest.main()
