"""
scrapengine/scrapers/starhealth_news tests
"""
import os
import unittest
import random
from Scrapengine.scrapers import starhealth_news
from Scrapengine.configs import ARCHIVE

class StarhealthnewsScraperTestCase(unittest.TestCase):
    
    def setUp(self,):
        self.foo = True

    def test_get_articles(self, ):
        count = random.randint(1,50)
        resp = starhealth_news.get_articles(count)
        self.assertIsInstance(resp, list)
        self.assertEqual(len(resp), count)

    def test_output(self, ):
        test_output_file = "starhealth_news-tests"
        for _file in os.listdir(ARCHIVE):
            if _file.endswith('json') and _file.startswith(test_output_file):
                # delete output files generated by the unit tests
                os.remove("%s/%s" % (ARCHIVE, _file))
        
        sample = ["foo", "bar"]
        filename = test_output_file
        starhealth_news.output(sample, outputfile=filename)

        generated = False
        for _file in os.listdir(ARCHIVE):
            if _file.endswith('json') and _file.startswith(test_output_file):
                generated = True
                os.remove("%s/%s" % (ARCHIVE, _file))
                break
        self.assertTrue(generated, msg="Output not generated")


if __name__ == '__main__':
    unittest.main()
